### ISSUE TITLE
Timer 객체 생성하기

### ISSUE THREAD

**Issue by mastojun** [DPStudy/LifeGame#1]
Observer 객체를 등록 가능하고, 설정된 주기적으로 Observer list에게 모두 tick을 날려주는 Timer 객체 생성하기
Main Thread와는 별도로 동작을 해야함 (java thread 객체 구현)

**Comment by mastojun** [comment]
@ahongdaong88 구현 부탁해!! ㅋㅋㅋㅋ 요!

**Comment by ahongdaong88** [comment]
제가 드디어.... 타이머 구현하였습니당 ㅠ

**Comment by mastojun** [comment]
커뮤니케이션은 #2 에서 진행!
